client-http.cxx: Fix build error rpmFreeCrypto not declared
rpm-4.18.0 moved the declaration of rpmFreeCrypto into rpm/rpmcrypto.h.

Include this header in client-http.cxx when required in order to avoid
the following error:

 CXX      stap_gen_cert-util.o
../systemtap/client-http.cxx: In member function ‘std::string http_client::get_rpmname(std::string&)’:
../systemtap/client-http.cxx:482:5: error: ‘rpmFreeCrypto’ was not declared in this scope
  482 |     rpmFreeCrypto ();
      |     ^~~~~~~~~~~~~

See https://sourceware.org/bugzilla/show_bug.cgi?id=29094