translate.cxx: Fix out-of-bounds vector access
The following error was found by building stap with
-D_GLIBCXX_DEBUG and -D_GLIBCXX_DEBUG_PEDANTIC:

    /usr/include/c++/13/debug/vector:442:
    In function:
        std::debug::vector<_Tp, _Allocator>::reference std::debug::vector<_Tp,
        _Allocator>::operator[](size_type) [with _Tp = bool; _Allocator =
        std::allocator<bool>; reference = std::vector<bool, std::allocator<bool>
        >::reference; size_type = long unsigned int]

    Error: attempt to subscript container with out-of-bounds index 1, but
    container only holds 1 elements.

    Objects involved in the operation:
        sequence "this" @ 0x7fffffff8e70 {
          type = std::debug::vector<bool, std::allocator<bool> >;
        }

This is caused by an incorrectly sized vector in
c_unparser::visit_functioncall.  Fix this by ensuring that
the vector cp_args has a size equal to the number of arguments
of the functioncall being visited.