tapsets.cxx: fix the build against upcoming `gcc-16` (-Werror=unused-but-set-variable)
`gcc-16` expanded detection of unused variables in https://gcc.gnu.org/PR44677.
As a result `systemtap` fails the ubild now as:

    tapsets.cxx: In member function 'virtual void dwarf_derived_probe::emit_probe_local_init(systemtap_session&, translator_output*)':
    tapsets.cxx:6222:20: error: variable 'i' set but not used [-Werror=unused-but-set-variable=]
     6222 |           unsigned i = 0;
          |                    ^

Let's drop unused variable.