PR33978: error: implicit declaration of function ‘__cond_lock’
The __cond_lock macro was dropped as part of linux commit
e4588c25c9d122b5847b88e18b184404b6959160 .  This commit
reflects that on the systemtap side.