Prevent redefinition of ‘struct unwind_cache’
Linux commit b9c73524106e1c0c857006fb9ff2e5a510dc4021 adds
struct unwind_cache to include/linux/unwind_deferred_types.h.
This causes pass-4 systemtap/runtime/unwind/unwind.h:528:8:
error: redefinition of ‘struct unwind_cache’.  Prevent it.