Add missing header to fix an s390x specific compile problem
Add include unistd.h because of the close() call.
The error message on s390x/rhel8 was:

-------------------8<----------------------------------------------------
tapset-debuginfod.cxx:44:3: error: 'close' was not declared in this scope
   close(metadata_fd);
   ^~~~~
tapset-debuginfod.cxx:44:3: note: suggested alternative: 'pclose'
   close(metadata_fd);
   ^~~~~
   pclose
make[3]: *** [Makefile:1756: stap-tapset-debuginfod.o] Error 1
make[3]: *** Waiting for unfinished jobs....
-------------------8<----------------------------------------------------