PR33978: Avoid error: ‘__lock_task_sighand’ undeclared here
The following run time error was hit with kernel-7.0.0-0.rc2.21.fc45.x86_64:

Pass 3: translated to C into "/tmp/stap51VR9s/stap_20c366cdb7027c0ced73611307c798c0_67698_src.c" using 503848virt/263556res/19864shr/277972data kb, in 0usr/0sys/1real ms.
In file included from /usr/local/share/systemtap/runtime/linux/task_finder2.c:4,
                 from /usr/local/share/systemtap/runtime/linux/task_finder.c:15,
                 from /usr/local/share/systemtap/runtime/linux/runtime.h:347,
                 from /usr/local/share/systemtap/runtime/runtime.h:26,
                 from stap_20c366cdb7027c0ced73611307c798c0_67698_src.c:21:
/usr/local/share/systemtap/runtime/stp_utrace.c:318:17: error: ‘__lock_task_sighand’ undeclared here (not in a function); did you mean ‘unlock_task_sighand’?
  318 | typedef typeof(&__lock_task_sighand) __lock_task_sighand_fn;
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 unlock_task_sighand
/usr/local/share/systemtap/runtime/stp_utrace.c: In function ‘stp_lock_task_sighand’:
/usr/local/share/systemtap/runtime/stp_utrace.c:319:72: error: invalid type argument of unary ‘*’ (have ‘int’)
  319 | #define __lock_task_sighand(a,b) ibt_wrapper(struct sighand_struct *, (* (__lock_task_sighand_fn)kallsyms___lock_task_sighand)((a), (b)))
      |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/share/systemtap/runtime/linux/runtime.h:317:21: note: in definition of macro ‘ibt_wrapper’
  317 |   rettype retval = (function);                  \
      |                     ^~~~~~~~
/usr/local/share/systemtap/runtime/stp_utrace.c:332:15: note: in expansion of macro ‘__lock_task_sighand’
  332 |         ret = __lock_task_sighand(tsk, flags);
      |               ^~~~~~~~~~~~~~~~~~~
make[2]: *** [/usr/src/kernels/7.0.0-0.rc2.21.fc45.x86_64/scripts/Makefile.build:289: stap_20c366cdb7027c0ced73611307c798c0_67698_src.o] Error 1

This error is a consequence of upstream kernel commit e4588c25c9d122b5847b88e18b184404b6959160
which drops __lock_task_sighand() and inlined variant of function
lock_task_sighand().  Instead it does introduce lock_task_sighand()
which is not inlined.

This update uses STAPCONF_ATOMIC_DEC_AND_LOCK_EXPORTED_PR33978 as an
indirect indicator that kernel commit e4588c25c9d122b5847b88e18b184404b6959160
was applied. That seems more robust that gating on the kernel version
which is proven to be unreliable with some distribution kernels).

If kernel commit e4588c25c9d122b5847b88e18b184404b6959160 is in place,
extern struct sighand_struct *lock_task_sighand() can be directly used.