Fix `-Werror,-Wtautological-constant-out-of-range-compare` build error
Clang-22 fails to build with the following error:
```
stapbpf.cxx:2033:21: error: result of comparison of constant 2305843009213693951 with expression of
      type 'unsigned int' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
 2033 |   if (n_active_cpus > (size_t)-1 / sizeof(struct pollfd))
      |       ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
as `n_active_cpus` is of type `unsigned` (32-bit), so it should be
compared against another `unsigned`.

Signed-off-by: Sv. Lockal <lockalsash@gmail.com>