elaborate.cxx: fix 32-bit build
Without the change the build fails on i686-linux as:

    elaborate.cxx:5119:33: error:
      format '%ld' expects argument of type 'long int',
      but argument 2 has type 'int64_t' {aka 'long long int'} [-Werror=format=]
     5119 |       session.print_warning (_F("Collapsing unresolved @define to %ld [stapprobes]", value), e->tok);
          |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~