Fix compilation with Clang
Clang-22 fails to compile with errors like:
```
bpfinterp.cxx:1098:18: error: case value is not a constant expression
 1098 |             case bpf::BPF_FUNC_str_concat:
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
```

GCC accepts const variables, but Clang enforces the standard more
strictly. Using enum allows both compilers to accept the code, but
requires cast from bpf::(unnamed enum) to bpf_func_id.

Signed-off-by: Sv. Lockal <lockalsash@gmail.com>